services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=gobookapiuser
      - POSTGRES_PASSWORD=gobookapipassword
    ports:
      - "5432:5432"
    volumes: 
      - postgresdbdata:/var/lib/postgresql/data
    networks:
      - gobookapinet
  gobookapi:
    build: .
    depends_on:
      - postgresdb
    networks:
      - gobookapinet
    ports:
      - "8080:8080"

volumes:
  postgresdbdata:
    driver: local

networks:
  gobookapinet:
    driver: bridge

