version: '3.1'
services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=gobookapiuser
      - POSTGRES_PASSWORD=gobookapipassword
    ports:
      - '5432:5432'
    volumes: 
      - postgresdbdata:/var/lib/postgresql/data
      
volumes:
  postgresdbdata:
    driver: local