services:
  database:
    container_name: bookrestapidatabase
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/scripts/:/docker-entrypoint-initdb.d/
    networks:
      - bookrestapinet
  server:
    container_name: bookrestapiserver
    build: .
    depends_on:
      - database
    networks:
      - bookrestapinet
    ports:
      - "8080:8080"

volumes:
  bookrestapidata:
    driver: local

networks:
  bookrestapinet:
    driver: bridge
